// Copies the advisor system prompt from prompts/radgivaren.md into the edge
// function bundle. Everything after the first line that is exactly "---" is
// the prompt. Run: node scripts/sync-prompt.mjs   (add --check to verify only)
import { readFileSync, writeFileSync, existsSync } from "node:fs";

const src = new URL("../prompts/radgivaren.md", import.meta.url);
const out = new URL("../supabase/functions/_shared/prompt.ts", import.meta.url);

const md = readFileSync(src, "utf8");
const lines = md.split("\n");
const sep = lines.findIndex((l) => l.trim() === "---");
if (sep === -1) throw new Error("prompts/radgivaren.md: no '---' separator found");
const prompt = lines.slice(sep + 1).join("\n").trim();

const ts =
  "// GENERATED by scripts/sync-prompt.mjs from prompts/radgivaren.md. Do not edit.\n" +
  `export const SYSTEM_PROMPT = ${JSON.stringify(prompt)};\n`;

if (process.argv.includes("--check")) {
  const current = existsSync(out) ? readFileSync(out, "utf8") : "";
  if (current !== ts) {
    console.error("prompt.ts is out of date. Run: node scripts/sync-prompt.mjs");
    process.exit(1);
  }
  console.log("prompt.ts is up to date");
} else {
  writeFileSync(out, ts);
  console.log(`Wrote ${out.pathname} (${prompt.length} chars)`);
}
